name: tdmpc
channels:
  - defaults
dependencies:
  - python=3.8
  - pytorch=2.3
  - torchvision
  - cudatoolkit=11.8
  - pip
  - pip:
    - termcolor
    - omegaconf
    - gym==0.21.0
    - dm-control==0.0.403778684
    - pandas
    - wandb
    - moviepy
    - imageio
